version: "3.8"
services:
  db:
    image: postgres:12.1
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    env_file:
      - environment.env

  server:
    image: node:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/server
    working_dir: /usr/server
    command: "npm run start"
    depends_on:
      - db

volumes:
  pg_data:
    driver: local
